language: node_js
node_js:
- 4

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: required
dist: trusty
  
env:
- CXX="g++-4.8" KIBANA_VERSION="5.0.0-beta1" ELASTICSEARCH_VERSION="5.0.0-beta1"


before_script:
- npm install -g gulp
- wget -O kibana.tar.gz https://github.com/elastic/kibana/archive/v${KIBANA_VERSION}.tar.gz
- mkdir -p kibana && tar -zxf kibana.tar.gz -C kibana --strip-components=1
- sh -c 'cd kibana && npm install'
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.deb && sudo dpkg -i --force-confnew elasticsearch-${ELASTICSEARCH_VERSION}.deb && sudo service elasticsearch restart
- curl -O https://raw.githubusercontent.com/rockymadden/transfer-cli/master/src/transfer && chmod +x transfer
- pip install mkdocs

script:
- mkdocs build
- gulp build
- gulp package
- bash test.sh

deploy:
  provider: releases
  file_glob: true
  api_key:
    secure: 2e958021848eb80b4f2291e38c85d78734f67338
  file: target/timelion-google-analytics-*.zip
  skip_cleanup: true
  on:
    repo: bahaaldine/timelion-google-analytics
    tags: true
    node: 4